# services:
# - type: pserv
#   repo: https://github.com/Hari13-12/Voice-agent.git

#   # Change this to the path containing your Dockerfile
#   rootDir: RuTx-Render

#   name: agent-example
#   runtime: docker

#   # Free plan is not available for private services
#   plan: starter

#   # Environment variables are stored in a group
#   # created in the Render dashboard.
#   envVars:
#   - fromGroup: Visits-voice-agent
#   region: virginia

#   # 300s is the standard allowed maximum. Talk to render.com support if you need this increased.
#   maxShutdownDelaySeconds: 300

#   # Sane defaults
#   scaling:
#     minInstances: 1
#     maxInstances: 4
#     targetCPUPercent: 60
#     targetMemoryPercent: 60
# version: "1"

services:
  - type: web
    name: visit-agent-livekit
    repo: https://github.com/Hari13-12/Voice-agent.git
    rootDir: RuTx-render
    runtime: docker
    plan: free
    envVars:
      - fromGroup: Visits-voice-agent
    region: virginia
version: "1"
